#include "autogeneratedfieldswindow.h"
#include "ui_autogeneratedfieldswindow.h"

AutogeneratedFieldsWindow::AutogeneratedFieldsWindow(QWidget *parent) :
    QMainWindow(parent),
    ui(new Ui::AutogeneratedFieldsWindow)
{
    ui->setupUi(this);
}

AutogeneratedFieldsWindow::~AutogeneratedFieldsWindow()
{
    delete ui;
}
