#ifndef AUTOGENERATEDFIELDSWINDOW_H
#define AUTOGENERATEDFIELDSWINDOW_H

#include <QMainWindow>

namespace Ui {
class AutogeneratedFieldsWindow;
}

class AutogeneratedFieldsWindow : public QMainWindow
{
    Q_OBJECT

public:
    explicit AutogeneratedFieldsWindow(QWidget *parent = nullptr);
    ~AutogeneratedFieldsWindow();

private:
    Ui::AutogeneratedFieldsWindow *ui;
};

#endif // AUTOGENERATEDFIELDSWINDOW_H
